In [1]:
import shutil
from pathlib import Path
import os
import pandas as pd

C:\Users\sshri\AppData\Local\Temp\ipykernel_14856\197364822.py:4: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
import tensorflow as tf 

In [3]:
data = pd.read_csv('../Test_Data/summan.smr')

In [4]:
data.head()

img_name        lat        lon  \
0  _panoid_-1tN4lEA-abrRGZw66d34Q_heading_294_pit... -23.549251 -46.541349   
1  _panoid_-2bCdOFUdXRl3YZkXZ2KVw_heading_224_pit... -23.524786 -46.695520   
2  _panoid_-2bCdOFUdXRl3YZkXZ2KVw_heading_334_pit... -23.524786 -46.695520   
3  _panoid_-2yEbA_Nn547hSIMJqXFmg_heading_133_pit... -23.564307 -46.755973   
4  _panoid_-2yEbA_Nn547hSIMJqXFmg_heading_248_pit... -23.564307 -46.755973   

   heading  pitch timestamp status  Tree  Pole w/ wire  Intersection  
0      294     -1   2019-03   free     1             1             0  
1      224      4   2019-04   free     1             1             1  
2      334      4   2019-04   free     1             1             1  
3      133      6   2019-05   free     1             0             0  
4      248      6   2019-05   free     1             0             0

In [5]:
from PIL import Image
import os

In [6]:
# Define the path to your dataset
dataset_path = '../Test_Data/'

# Create a list to store file paths and corresponding labels
file_paths = []
labels = []

In [7]:

for folder_name in os.listdir(dataset_path):
    folder_path = os.path.join(dataset_path, folder_name)
    print(folder_path)

../Test_Data/summan.smr
../Test_Data/summan3220unk.smr
../Test_Data/_panoid_--2PQ1U5-r20HZJQySYogw_heading_324_pitch_2.png
../Test_Data/_panoid_--u5-wmNO8XK1UROQ-S0pQ_heading_129_pitch_0.png
../Test_Data/_panoid_-1tN4lEA-abrRGZw66d34Q_heading_294_pitch_-1.png
../Test_Data/_panoid_-2bCdOFUdXRl3YZkXZ2KVw_heading_224_pitch_4.png
../Test_Data/_panoid_-2bCdOFUdXRl3YZkXZ2KVw_heading_334_pitch_4.png
../Test_Data/_panoid_-2yEbA_Nn547hSIMJqXFmg_heading_133_pitch_6.png
../Test_Data/_panoid_-2yEbA_Nn547hSIMJqXFmg_heading_248_pitch_6.png
../Test_Data/_panoid_-2yEbA_Nn547hSIMJqXFmg_heading_29_pitch_6.png
../Test_Data/_panoid_-2yEbA_Nn547hSIMJqXFmg_heading_314_pitch_6.png
../Test_Data/_panoid_-2yEbA_Nn547hSIMJqXFmg_heading_60_pitch_6.png
../Test_Data/_panoid_-2yEbA_Nn547hSIMJqXFmg_heading_99_pitch_6.png
../Test_Data/_panoid_-3Xd4HgB8GmKCDSrR8IKbw_heading_266_pitch_0.png
../Test_Data/_panoid_-4cTOC0hOIukonv94Y-v-w_heading_288_pitch_0.png
../Test_Data/_panoid_-4eAp0JgEohAH8c8EsHxmA_heading_298_pitch_1

In [8]:
data['img_name'] = '../Test_Data/' + data['img_name']
data

img_name        lat        lon  \
0     ../Test_Data/_panoid_-1tN4lEA-abrRGZw66d34Q_he... -23.549251 -46.541349   
1     ../Test_Data/_panoid_-2bCdOFUdXRl3YZkXZ2KVw_he... -23.524786 -46.695520   
2     ../Test_Data/_panoid_-2bCdOFUdXRl3YZkXZ2KVw_he... -23.524786 -46.695520   
3     ../Test_Data/_panoid_-2yEbA_Nn547hSIMJqXFmg_he... -23.564307 -46.755973   
4     ../Test_Data/_panoid_-2yEbA_Nn547hSIMJqXFmg_he... -23.564307 -46.755973   
...                                                 ...        ...        ...   
996   ../Test_Data/_panoid_1Jiuw5GffGA2SfD2AomXSA_he... -30.163288 -51.173273   
997   ../Test_Data/_panoid_1Jiuw5GffGA2SfD2AomXSA_he... -30.163288 -51.173273   
998   ../Test_Data/_panoid_0dbEfK0X8xDv78-LdVz2vg_he... -30.161117 -51.174357   
999   ../Test_Data/_panoid_0dbEfK0X8xDv78-LdVz2vg_he... -30.161117 -51.174357   
1000  ../Test_Data/_panoid_0dZLi4-ZBL7BRymFjRezmg_he... -30.068398 -51.182170   

      heading  pitch timestamp status  Tree  Pole w/ wire  Intersection  
0         294     -1   2019-03   free     1             1             0  
1         224      4   2019-04   free     1             1             1  
2         334      4   2019-04   free     1             1             1  
3         133      6   2019-05   free     1             0             0  
4         248      6   2019-05   free     1             0             0  
...       ...    ...       ...    ...   ...           ...           ...  
996        10      1   2019-02   free     1             1             0  
997        88      1   2019-02   free     1             1             0  
998       219      2   2019-02   free     1             1             0  
999        35      2   2019-02   free     1             1             0  
1000      217      8   2019-04   free     1             1             1  

[1001 rows x 10 columns]

In [9]:
from sklearn.model_selection import train_test_split

train_df, val_df = train_test_split(data, test_size=0.2, random_state=42)

In [10]:
train_df

img_name        lat        lon  \
535  ../Test_Data/_panoid_-qW3U3yMEE8vz47tLnu1eg_he... -30.016563 -51.172947   
696  ../Test_Data/_panoid_2HlR4Kl9I4I7ZiwABtpsLg_he... -30.027452 -51.172601   
557  ../Test_Data/_panoid_00Y2OYhvDszADp7kTpQPSw_he... -30.034689 -51.177541   
643  ../Test_Data/_panoid_1oqQcQwNkHIpC62HBv2B3A_he... -30.018040 -51.183167   
597  ../Test_Data/_panoid_0Ral0UQRhTFsLf2RDhJ1RQ_he... -30.027262 -51.193711   
..                                                 ...        ...        ...   
106  ../Test_Data/_panoid_-ok74tT3usmMUQlDzjgj8Q_he... -23.531287 -46.688717   
270  ../Test_Data/_panoid_0m2TJlVFNDoDxQxGL_rakA_he... -23.566704 -46.746582   
860  ../Test_Data/_panoid_4t5jiVQ-oVoULwZg9huo9w_he... -30.033511 -51.191859   
435  ../Test_Data/_panoid_1hVtkIpXb6jQXtHVLLl5Sw_he... -23.533273 -46.700341   
102  ../Test_Data/_panoid_-ofjwRvu_CtaQiBRxLgxDQ_he... -23.529712 -46.697962   

     heading  pitch timestamp status  Tree  Pole w/ wire  Intersection  
535       74      0   2019-04   free     1             1             1  
696       20      0   2019-04   free     1             1             0  
557       62     -1   2019-08   free     1             1             0  
643      200      0   2019-04   free     1             1             1  
597      180     -1   2019-04   free     1             1             0  
..       ...    ...       ...    ...   ...           ...           ...  
106      331     -2   2019-04   free     1             1             1  
270      307      6   2015-11   free     1             1             0  
860      139      0   2019-04   free     1             1             1  
435      147     -2   2019-04   free     1             1             0  
102      211     -3   2017-08   free     1             1             1  

[800 rows x 10 columns]

In [69]:
train_dataset = tf.data.Dataset.from_tensor_slices(
    (train_df['img_name'].values,train_df['Intersection'],train_df['Pole w/ wire'].values,train_df['Tree'])
)
print(train_dataset)

<TensorSliceDataset element_spec=(TensorSpec(shape=(), dtype=tf.string, name=None), TensorSpec(shape=(), dtype=tf.int64, name=None), TensorSpec(shape=(), dtype=tf.int64, name=None), TensorSpec(shape=(), dtype=tf.int64, name=None))>


In [70]:
print(next(iter(train_dataset)))

(<tf.Tensor: shape=(), dtype=string, numpy=b'../Test_Data/_panoid_-qW3U3yMEE8vz47tLnu1eg_heading_74_pitch_0.png'>, <tf.Tensor: shape=(), dtype=int64, numpy=1>, <tf.Tensor: shape=(), dtype=int64, numpy=1>, <tf.Tensor: shape=(), dtype=int64, numpy=1>)


In [71]:
val_dataset = tf.data.Dataset.from_tensor_slices(
    (val_df['img_name'].values,val_df['Intersection'],val_df['Pole w/ wire'].values,val_df['Tree'])
)

In [72]:
x = 0
for i in val_dataset:  
    print(i)

(<tf.Tensor: shape=(), dtype=string, numpy=b'../Test_Data/_panoid_-iajR7i019p5y3804BFsHQ_heading_16_pitch_0.png'>, <tf.Tensor: shape=(), dtype=int64, numpy=1>, <tf.Tensor: shape=(), dtype=int64, numpy=1>, <tf.Tensor: shape=(), dtype=int64, numpy=1>)
(<tf.Tensor: shape=(), dtype=string, numpy=b'../Test_Data/_panoid_663_1Lm2ffFgQ8Mc-LkkYQ_heading_276_pitch_3.png'>, <tf.Tensor: shape=(), dtype=int64, numpy=1>, <tf.Tensor: shape=(), dtype=int64, numpy=1>, <tf.Tensor: shape=(), dtype=int64, numpy=1>)
(<tf.Tensor: shape=(), dtype=string, numpy=b'../Test_Data/_panoid_35pYIATDnbbUSXxv3S5cqg_heading_220_pitch_-2.png'>, <tf.Tensor: shape=(), dtype=int64, numpy=1>, <tf.Tensor: shape=(), dtype=int64, numpy=1>, <tf.Tensor: shape=(), dtype=int64, numpy=1>)
(<tf.Tensor: shape=(), dtype=string, numpy=b'../Test_Data/_panoid_6mzXYi24lkzV8qCqUrjNeQ_heading_286_pitch_0.png'>, <tf.Tensor: shape=(), dtype=int64, numpy=0>, <tf.Tensor: shape=(), dtype=int64, numpy=1>, <tf.Tensor: shape=(), dtype=int64, numpy=

In [73]:
def load_and_preprocess_image(file_path, intersection, pole_with_wire, tree):
    print(file_path)
    image = tf.io.read_file(file_path)
    image = tf.image.decode_image(image, channels=3)  # Adjust channels based on your images
    image.set_shape([640, 640, 3])  # Assuming 3 channels for RGB images
    image = tf.image.resize(image, (640, 640))  # Adjust size as needed
    image = image / 255.0  # Normalize pixel values to the range [0, 1]
    return image,intersection,pole_with_wire,tree

In [74]:
train_dataset = train_dataset.map(load_and_preprocess_image)

Tensor("args_0:0", shape=(), dtype=string)


In [75]:
train_dataset = train_dataset.shuffle(buffer_size=len(train_df))
train_dataset = train_dataset.batch(1)

In [76]:
val_dataset = val_dataset.map(load_and_preprocess_image)

Tensor("args_0:0", shape=(), dtype=string)


In [77]:
val_dataset = val_dataset.shuffle(buffer_size=len(train_df))
val_dataset = val_dataset.batch(1)

In [78]:
x = 0
y = None
for i in train_dataset:  # Adjust the number as needed
    print(i[0].shape)

(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 3)
(1, 640, 640, 

In [79]:
base_model = tf.keras.applications.MobileNetV2(input_shape=(640,640,3),
                                                           include_top=False,
                                                           weights='imagenet')
base_model.trainable = False

In [80]:
from tensorflow.keras import layers, models


# Freeze the convolutional layers
base_model.trainable = False

# Create the custom classifier model
model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(1000, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(500, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(1, activation='sigmoid')  # Assuming binary classification
])

# Compile the model
model.compile(optimizer='adam',
              loss='binary_crossentropy',  # Adjust the loss function based on your task
              metrics=['accuracy'],
              )

# Display the model summary
model.summary()


Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 mobilenetv2_1.00_224 (Funct  (None, 20, 20, 1280)     2257984   
 ional)                                                          
                                                                 
 global_average_pooling2d_5   (None, 1280)             0         
 (GlobalAveragePooling2D)                                        
                                                                 
 dense_15 (Dense)            (None, 1000)              1281000   
                                                                 
 dropout_10 (Dropout)        (None, 1000)              0         
                                                                 
 dense_16 (Dense)            (None, 500)               500500    
                                                                 
 dropout_11 (Dropout)        (None, 500)              

In [81]:
model.fit(train_dataset, epochs=10)

Epoch 1/10


ValueError: in user code:

    File "c:\Users\sshri\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 1160, in train_function  *
        return step_function(self, iterator)
    File "c:\Users\sshri\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 1146, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\sshri\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 1135, in run_step  **
        outputs = model.train_step(data)
    File "c:\Users\sshri\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 990, in train_step
        x, y, sample_weight = data_adapter.unpack_x_y_sample_weight(data)
    File "c:\Users\sshri\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\data_adapter.py", line 1774, in unpack_x_y_sample_weight
        raise ValueError(error_msg)

    ValueError: Data is expected to be in format `x`, `(x,)`, `(x, y)`, or `(x, y, sample_weight)`, found: (<tf.Tensor 'IteratorGetNext:0' shape=(None, 640, 640, 3) dtype=float32>, <tf.Tensor 'IteratorGetNext:1' shape=(None,) dtype=int64>, <tf.Tensor 'IteratorGetNext:2' shape=(None,) dtype=int64>, <tf.Tensor 'IteratorGetNext:3' shape=(None,) dtype=int64>)


In [24]:
model.evaluate(train_dataset)

800/800 [==============================] - 17s 20ms/step - loss: 0.1704 - accuracy: 0.9725


[0.170397087931633, 0.9725000262260437]

In [25]:
model.evaluate(val_dataset)

201/201 [==============================] - 4s 20ms/step - loss: 0.9471 - accuracy: 0.7214


[0.9470692276954651, 0.7213930487632751]

In [26]:
x = model.predict(val_dataset)

201/201 [==============================] - 4s 19ms/step
